/* CREATE TABLES FOR DATABASE sauna */
CREATE TABLE sensor_values (
    id INT AUTO_INCREMENT PRIMARY KEY,
    recorded TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    temp FLOAT  NOT NULL,
    hum FLOAT NOT NULL
)